# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#pr:
# branches:
#   include:
#     - '*'  # must quote since "*" is a YAML reserved character; we want a string 

pr: none

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: MyGitHub_splitman2run # The name used to reference this repository in the checkout step
      type: github
      endpoint: lezhumain
      name: lezhumain/SplitMan2-run

variables:
  - group: var_groupe
  - name: IMAGE
    value: splitman2nginx
  - name: SREPO
    value: SplitMan2-nginx

stages:
  - stage: Build
    jobs:
      - job: Build_Docker_Containers
        steps:
          - checkout: self
          - checkout: MyGitHub_splitman2run

          - task: DownloadSecureFile@1
            name: sslCert
            displayName: 'Download cert'
            inputs:
              secureFile: 'letsencrypt.crt'

          - task: DownloadSecureFile@1
            name: sslKey
            displayName: 'Download key'
            inputs:
              secureFile: 'letsencrypt.key'

          - script: |
              cd "$SREPO"
              TARGET_DIR="/home/$(whoami)/.ssl"
              echo "TARGET_DIR: $TARGET_DIR"
              mkdir -p "$TARGET_DIR"
              sudo cp $(sslCert.secureFilePath) "$TARGET_DIR/letsencrypt.crt"
              sudo cp $(sslKey.secureFilePath) "$TARGET_DIR/letsencrypt.key"
              sudo chown -R "$(whoami)" "$TARGET_DIR"
              chmod 600 "$TARGET_DIR"/*
            displayName: 'Prepare SSL key and cert'

          - script: |
              cd "$SREPO"
              bash ../SplitMan2-run/run_docker_e2e.sh "$DEBIAN_IP" "https" "$SREPO"
              docker save "$IMAGE" -o "$(Build.ArtifactStagingDirectory)/$IMAGE.tar"
            env:
              MONGO_USER: $(MONGO_USER)
              MONGO_PASS: $(MONGO_PASS)
              DEBIAN_IP: $(DEBIAN_IP)
            displayName: 'Build containers'

          - publish: '$(Build.ArtifactStagingDirectory)/$(IMAGE).tar'
            displayName: 'Publish tar image'
            artifact: $(IMAGE)_tar
           
